version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: ns-backend
    ports:
      - "4001:4001"
    volumes:
      - ./backend/db:/app/db
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: ns-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always